.PHONY: clean All

All:
	@echo "----------Building project:[ lib - Debug ]----------"
	@"$(MAKE)" -f  "lib.mk"
clean:
	@echo "----------Cleaning project:[ lib - Debug ]----------"
	@"$(MAKE)" -f  "lib.mk" clean
