.PHONY: clean All

All:
	@echo "----------Building project:[ mylib - Debug ]----------"
	@"$(MAKE)" -f  "mylib.mk"
clean:
	@echo "----------Cleaning project:[ mylib - Debug ]----------"
	@"$(MAKE)" -f  "mylib.mk" clean
